# Generated by Django 3.0.2 on 2020-01-11 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='description',
            field=models.CharField(default='product/service purchased', max_length=100),
        ),
        migrations.AddField(
            model_name='payment',
            name='reference',
            field=models.CharField(default='AM61SK', max_length=6),
        ),
        migrations.AddField(
            model_name='payment',
            name='type',
            field=models.CharField(default='MERCHANT', max_length=9),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=200000),
        ),
    ]
