# Generated by Django 3.0.2 on 2020-01-11 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20200111_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='reference',
            field=models.CharField(max_length=6),
        ),
    ]
